default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: search_n_export


production:
  <<: *default
  database: search_n_export_production
  username: search_n_export
  password: <%= ENV['SEARCH_N_EXPORT'] %>

test:
  <<: *default
  database: search_n_export_test
